// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace BankAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230826072508_InitData")]
    partial class InitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.TestClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TestClass");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d4f7211-ed1b-4957-afa9-34134cacd1a2"),
                            Address = "456, Wall Street"
                        },
                        new
                        {
                            Id = new Guid("8b4216be-c6fe-4178-8da1-59341179dd75"),
                            Address = "323, Wyoming street"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
